services:
  db:
    image: postgres:latest
    container_name: c_db_auth
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: JavaAuthDb
    ports:
      - "5400:5432"
    volumes:
      - java_auth_db_volume:/var/lib/postgresql/data

volumes:
  java_auth_db_volume: